baseURL: https://crses.de
languageCode: de-de
title: Crses
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
    # Logo (from static/images/logos/___)
    image: logos/logo-color.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: C[ou]rses. Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Starten Sie noch heute mit Ihrer eigenen Kursverwaltungsseite
    # Button text
    buttontext: Mehr Informationen
    # Where the main hero button links to
    buttonlink: "/features"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    #   - systek
    #   - tribe
    #   - kromo
    #   - infinite
    #   - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    # - title: Details
    #   url: /features
    - title: Impressum
      url: /imprint
    # - title: Log in
    #   url: /
    #   sublinks:
    #     - title: Dropdown item
    #       url: /
    #     - title: Dropdown item
    #       url: /
    #     - title: Dropdown item
    #       url: /
    # - title: Sign up
    #   url: /
    #   button: true
    # Logo (from /images/logos/___.svg)
  section1:
    title: Flexibilit채t & Belastbarkeit
    subtitle:
    tiles:
      - title: Plattformunabh채ngig
        icon: laptop-globe
        text: Voller Komfort im Browser von 체berall
        url: mailto:info@crses.de
        buttonText: Jetzt starten
      - title: Cloud Integration
        icon: laptop-cloud
        text: Sicherheit durch die Redundanz der Cloud
        url: mailto:info@crses.de
        buttonText: Jetzt starten
      - title: Erweiterbarkeit
        icon: plug-cloud
        text: Anpassungsf채higkeit auf spezielle Anforderungen
        url: mailto:info@crses.de
        buttonText: Jetzt starten
  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #     - title: Powerful and unified interface
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       # Icon (from /images/illustrations/icons/___.svg)
  #       icon: laptop-globe
  #     - title: Cross-device synchronisation
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       icon: doc-sync
  #     - title: Nomad system
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       icon: mobile-feed
  section3:
    title:
    subtitle:
    image: screenshots/application.jpg
    buttonText: Kontakt
    buttonLink: "mailto:info@crses.de"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #     - name: Irma Walters
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: Accountant
  #       img: 1
  #     - name: John Bradley
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: Financial Analyst
  #       img: 2
  #     - name: Gary Blackman
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: HR Manager
  #       img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: logo-color.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/Crses-GbR
        # Icons are from Font Awesome
        icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Information"
        links:
          - text: Impressum
            link: /imprint
          # - text: Why choose our product?
          #   link: /
          # - text: Compare features
          #   link: /
          # - text: Our roadmap
          #   link: /
          # - text: AGB
          #   link: /agb
      # column2:
      #   title: "Docs"
      #   links:
      #     - text: Get started
      #       link: /
      #     - text: User guides
      #       link: /
      #     - text: Admin guide
      #       link: /
      #     - text: Developers
      #       link: /
      # column3:
      #   title: "Blog"
      #   links:
      #     - text: Latest news
      #       link: /blog/first
      #     - text: Tech articles
      #       link: /blog/second
